### ISSUE TITLE
Unknown ABI option "Rust"

### ISSUE THREAD

**Issue by philberty** [Rust-GCC/gccrs#2034]
I tried this code: https://github.com/rust-lang/rust/blob/aa3ca1994904f2e056679fce1f185db8c7ed2703/src/test/ui/issue-10764.rs

```rust
fn f(_: extern "Rust" fn()) {}
extern fn bar() {}

fn main() { f(bar) }
//~^ ERROR mismatched types
```

I expected to see this happen: //~^ ERROR mismatched types

Instead, this happened:

```
<source>:1:9: error: unknown ABI option
    1 | fn f(_: extern "Rust" fn()) {}
      |         ^~~~~~
```

### Meta

- What version of Rust GCC were you using, git sha if possible. be27571c110d99fe55324a9c2b6622787b08fb52

**Comment by philberty** [comment]
This was fixed in 2d7661e76e1276b3661502022ecee2861d040026

**Comment by CohenArthur** [comment]
This should be fixed by #2162. I'll add the testcase in a small PR and close the issue

**Comment by CohenArthur** [comment]
Note that however we still do not handle the type mismatch which is an error in itself
